"""add_source_to_evaluations

Revision ID: acfb39f04c03
Revises: 00a3569bb1ee
Create Date: 2026-04-08 20:56:25.832507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfb39f04c03'
down_revision: Union[str, None] = '00a3569bb1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_evaluations', sa.Column('source', sa.String(length=20), nullable=False, server_default='MANUAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_evaluations', 'source')
    # ### end Alembic commands ###
